/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comdis_4.client;

/**
 *
 * @author aculledor
 */
public class VInicio extends javax.swing.JDialog {
    
    private final ClientGUI padre;

    /**
     * Creates new form VInicio
     */
    public VInicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (ClientGUI) parent;
    }
    
    public void setInteractive(Boolean bool){
        this.defaultBTN.setEnabled(bool);
        this.regisBTN.setEnabled(bool);
        this.signUpBTN.setEnabled(bool);
        this.nameTXT.setEnabled(bool);
        this.passTXT.setEnabled(bool);
        this.serverTXT.setEnabled(bool);
    }
    
    public void close(){
        this.padre.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signUpBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameTXT = new javax.swing.JTextField();
        regisBTN = new javax.swing.JButton();
        serverTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        defaultBTN = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(436, 340));
        setPreferredSize(new java.awt.Dimension(436, 340));
        setResizable(false);
        setSize(new java.awt.Dimension(436, 340));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(436, 340));
        jPanel1.setPreferredSize(new java.awt.Dimension(436, 340));

        signUpBTN.setBackground(new java.awt.Color(204, 204, 255));
        signUpBTN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        signUpBTN.setForeground(new java.awt.Color(0, 0, 0));
        signUpBTN.setText("Darse de alta");
        signUpBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contraseña");

        passTXT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        nameTXT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        regisBTN.setBackground(new java.awt.Color(255, 255, 204));
        regisBTN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        regisBTN.setForeground(new java.awt.Color(0, 0, 0));
        regisBTN.setText("Iniciar sesión");
        regisBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisBTNActionPerformed(evt);
            }
        });

        serverTXT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        serverTXT.setText("rmi://localhost:7777/P2P");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Server");

        defaultBTN.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        defaultBTN.setText("Default");
        defaultBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultBTNActionPerformed(evt);
            }
        });

        closeBTN.setBackground(new java.awt.Color(255, 102, 102));
        closeBTN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        closeBTN.setText("Cerrar");
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passTXT)
                    .addComponent(nameTXT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serverTXT)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(defaultBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeBTN))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(signUpBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(regisBTN)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(defaultBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regisBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 452, 379);
    }// </editor-fold>//GEN-END:initComponents

    private void regisBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisBTNActionPerformed
        // TODO add your handling code here:
        this.setInteractive(false);
        this.padre.connect(this.nameTXT.getText(), this.passTXT.getText(), this.serverTXT.getText());
    }//GEN-LAST:event_regisBTNActionPerformed

    private void defaultBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultBTNActionPerformed
        // TODO add your handling code here:
        this.serverTXT.setText("rmi://localhost:7777/P2P");
    }//GEN-LAST:event_defaultBTNActionPerformed

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBTNActionPerformed

    private void signUpBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBTNActionPerformed
        // TODO add your handling code here:
        this.setInteractive(false);
    }//GEN-LAST:event_signUpBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBTN;
    private javax.swing.JButton defaultBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTXT;
    private javax.swing.JTextField passTXT;
    private javax.swing.JButton regisBTN;
    private javax.swing.JTextField serverTXT;
    private javax.swing.JButton signUpBTN;
    // End of variables declaration//GEN-END:variables
}
